---
- hosts: localhost
  tasks:
    - name: Install packages
      apt: name="{{ item }}" state=present
      with_items:
        - vim
        - curl
        - git
        - python-pip
        - python-dev
        - openssh-server
        - iptables
        - dmenu
        - man-db
        - aspell